name: greet

on:
  push: 
    branches:
      - main
    paths:
      - .github/workflows/greet.yml

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.x'

      - name: run script
        run: python script.py "John Doe"
