name: code-coverage

on:
  push: 
    branches:
      - main
    paths: 
    - ./github/workflows/test.yml
  pull_request:
    branches:
      - main


jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v3

      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov 

      - name: run the code and code-coverage
        run: pytest --cov=. --cov-report=term-missing
        
